### ISSUE TITLE
如何集群配置

### ISSUE THREAD

**Issue by gongjie18675517757** [md-frank/file-service#3]
如何集群配置呢,是否有demo/doc

**Comment by md-frank** [comment]
可以参考这里：https://github.com/md-frank/file-service/wiki/%E5%A6%82%E4%BD%95%E9%85%8D%E7%BD%AE%E5%A4%9A%E5%8F%B0%E6%96%87%E4%BB%B6%E6%9C%8D%E5%8A%A1%E5%99%A8

**Comment by gongjie18675517757** [comment]
明白了,谢谢您

**Comment by zhchlmm** [comment]
> 可以参考这里：https://github.com/md-frank/file-service/wiki/%E5%A6%82%E4%BD%95%E9%85%8D%E7%BD%AE%E5%A4%9A%E5%8F%B0%E6%96%87%E4%BB%B6%E6%9C%8D%E5%8A%A1%E5%99%A8

请教一下，配置之后id=2的服务器AllowUpload=false，不接受上传，文件是如何分布到这台服务器的？

谢谢！
