### ISSUE TITLE
请教多文件服务器配置问题

### ISSUE THREAD

**Issue by zhchlmm** [md-frank/file-service#6]
[参考这里：https://github.com/md-frank/file-service/wiki/%E5%A6%82%E4%BD%95%E9%85%8D%E7%BD%AE%E5%A4%9A%E5%8F%B0%E6%96%87%E4%BB%B6%E6%9C%8D%E5%8A%A1%E5%99%A8](https://github.com/md-frank/file-service/wiki/%E5%A6%82%E4%BD%95%E9%85%8D%E7%BD%AE%E5%A4%9A%E5%8F%B0%E6%96%87%E4%BB%B6%E6%9C%8D%E5%8A%A1%E5%99%A8)

请教一下，配置之后id=2的服务器AllowUpload=false，不接受上传，文件是如何分布到这台服务器的？

谢谢！

**Comment by md-frank** [comment]
通常建议对客户端提供一个统一的上传入口，即只有一个服务器AllowUpload，上传服务器会根据权重（Weight）决定将文件存储在哪台服务器上

**Comment by zhchlmm** [comment]
明白了，多谢！
