### ISSUE TITLE
部署在linux 上会提示表不存在，脚本创建的表名都是小写的，程序里用File_ 

### ISSUE THREAD

**Issue by Laff80** [md-frank/file-service#8]
部署在linux 上会提示表不存在，脚本创建的表名都是小写的，程序里用File_ ， 这样就提示表名不存在

**Comment by md-frank** [comment]
修改Mysql配置：

vim /etc/my.cnf

// 在[mysqld]下增加
//忽略表名大小写
lower_case_table_names=1
